// ====== Colores de Badges ======
const BADGE_COLORS = {
  verde:   "#000000",
  amarillo:"#000000",
  rojo:    "#000000",
  gris:    "#000000",
  marron:  "#000000",
  morado:  "#000000",
  azul:    "#000000",
  celeste: "#000000",
  rosado:  "#000000",
};

// ====== Badges por Entrenador y Pokémon ======
// TODOS los pokémon de TRAINER_POKEMON tienen su badge individual aquí
const TRAINER_BADGES = {
  'Lorelei': {
    'Exeggutor': { text: 'Leyenda', color: 'celeste' },
    'Magnezone': { text: 'Leyenda', color: 'verde' },
    'Golduck': { text: 'Leyenda', color: 'marron' },
    'Mantine': { text: 'Leyenda', color: 'marron' },
    'Nidoking': { text: 'Leyenda', color: 'marron' },
    'Lapras': { text: 'Leyenda', color: 'celeste' },
    'Togekiss': { text: 'Leyenda', color: 'morado' },
    'Jynx': { text: 'Leyenda', color: 'celeste' },
    'Hariyama': { text: 'Leyenda', color: 'rojo' },
    'Nidoqueen': { text: 'Leyenda', color: 'marron' },
    'Bronzong': { text: 'Leyenda', color: 'celeste' },
    'Weavile': { text: 'Leyenda', color: 'azul' },
    'Dragonite': { text: 'Leyenda', color: 'rojo' },
    'Lucario': { text: 'Leyenda', color: 'rosado' },
    'Articuno': { text: 'Leyenda', color: 'celeste' },
    'Claydol': { text: 'Leyenda', color: 'azul' },
    'Slowbro': { text: 'Leyenda', color: 'morado' },
    'Raichu': { text: 'Leyenda', color: 'gris' },
    'Vileplume': { text: 'Leyenda', color: 'celeste' },
    'Chansey': { text: 'Leyenda', color: 'celeste' },
  },
  'Bruno_1': {
    'Lucario': { text: 'Leyenda', color: 'rosado' },
    'Slowbro': { text: 'Leyenda', color: 'amarillo' },
    'Muk': { text: 'Leyenda', color: 'verde' },
    'Ursaring': { text: 'Leyenda', color: 'amarillo' },
    'Steelix': { text: 'Leyenda', color: 'rojo' },
    'Staraptor': { text: 'Leyenda', color: 'marron' },
    'Machamp': { text: 'Leyenda', color: 'marron' },
    'Darmanitan': { text: 'Leyenda', color: 'rojo' },
    'Torterra': { text: 'Leyenda', color: 'marron' },
    'Blastoise': { text: 'Leyenda', color: 'celeste' },
    'Eelektross': { text: 'Leyenda', color: 'celeste' },
    'Metagross': { text: 'Leyenda', color: 'verde' },
    'Hitmonlee': { text: 'Leyenda', color: 'rojo' },
    'Gliscor': { text: 'Leyenda', color: 'verde' },
    'Electivire': { text: 'Leyenda', color: 'amarillo' },
    'Aggron': { text: 'Leyenda', color: 'rojo' },
    'Hitmonchan': { text: 'Leyenda', color: 'marron' },
    'Salamence': { text: 'Leyenda', color: 'celeste' },
    'Seismitoad': { text: 'Leyenda', color: 'rojo' },
    'Infernape': { text: 'Leyenda', color: 'marron' },
    'Rhyperior': { text: 'Leyenda', color: 'amarillo' },
    'Heracross': { text: 'Leyenda', color: 'rosado' },
    'Krookodile': { text: 'Leyenda', color: 'rojo' },
    'Hitmontop': { text: 'Leyenda', color: 'celeste' },
  },
  'Bruno_2': {
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Slowbro': { text: 'Leyenda', color: 'gris' },
    'Muk': { text: 'Leyenda', color: 'celeste' },
    'Ursaring': { text: 'Leyenda', color: 'amarillo' },
    'Steelix': { text: 'Leyenda', color: 'amarillo' },
    'Staraptor': { text: 'Leyenda', color: 'gris' },
    'Machamp': { text: 'Leyenda', color: 'marron' },
    'Darmanitan': { text: 'Leyenda', color: 'rojo' },
    'Torterra': { text: 'Leyenda', color: 'gris' },
    'Blastoise': { text: 'Leyenda', color: 'celeste' },
    'Eelektross': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'morado' },
    'Hitmonlee': { text: 'Leyenda', color: 'rojo' },
    'Gliscor': { text: 'Leyenda', color: 'azul' },
    'Electivire': { text: 'Leyenda', color: 'marron' },
    'Aggron': { text: 'Leyenda', color: 'celeste' },
    'Hitmonchan': { text: 'Leyenda', color: 'morado' },
    'Salamence': { text: 'Leyenda', color: 'azul' },
    'Seismitoad': { text: 'Leyenda', color: 'rojo' },
    'Krookodile': { text: 'Leyenda', color: 'marron' },
    'Hitmontop': { text: 'Leyenda', color: 'rojo' },
    'Poliwrath': { text: 'Leyenda', color: 'marron' },
    'Golem': { text: 'Leyenda', color: 'marron' },
    'Luxray': { text: 'Leyenda', color: 'morado' },
    'Blaziken': { text: 'Leyenda', color: 'marron' },
    'Heracross': { text: 'Leyenda', color: 'celeste' },
    'Kangaskhan': { text: 'Leyenda', color: 'celeste' },
  },
  'Agatha': {
    'Golduck': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'rosado' },
    'Muk': { text: 'Leyenda', color: 'celeste' },
    'Seismitoad': { text: 'Leyenda', color: 'rojo' },
    'Krookodile': { text: 'Leyenda', color: 'amarillo' },
    'Gyarados': { text: 'Leyenda', color: 'marron' },
    'Rotom Horno': { text: 'Leyenda', color: 'rojo' },
    'Shiftry': { text: 'Leyenda', color: 'marron' },
    'Gengar': { text: 'Leyenda', color: 'amarillo' },
    'Alakazam': { text: 'Leyenda', color: 'azul' },
    'Hydreigon': { text: 'Leyenda', color: 'rosado' },
    'Arbok': { text: 'Leyenda', color: 'celeste' },
    'Rotom Lavadora': { text: 'Leyenda', color: 'celeste' },
    'Umbreon': { text: 'Leyenda', color: 'marron' },
    'Marowak': { text: 'Leyenda', color: 'marron' },
    'Toxicroak': { text: 'Leyenda', color: 'rojo' },
    'Mandibuzz': { text: 'Leyenda', color: 'marron' },
    'Houndoom': { text: 'Leyenda', color: 'celeste' },
    'Rotom Ventilador': { text: 'Leyenda', color: 'azul' },
    'Crobat': { text: 'Leyenda', color: 'rojo' },
  },
  'Lance_1': {
    'Lapras': { text: 'Leyenda', color: 'marron' },
    'Dragonite': { text: 'Leyenda', color: 'rojo' },
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Steelix': { text: 'Leyenda', color: 'celeste' },
    'Eelektross': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'marron' },
    'Electivire': { text: 'Leyenda', color: 'amarillo' },
    'Infernape': { text: 'Leyenda', color: 'marron' },
    'Gyarados': { text: 'Leyenda', color: 'marron' },
    'Hydreigon': { text: 'Leyenda', color: 'rosado' },
    'Arbok': { text: 'Leyenda', color: 'marron' },
    'Charizard': { text: 'Leyenda', color: 'celeste' },
    'Scrafty': { text: 'Leyenda', color: 'amarillo' },
    'Feraligatr': { text: 'Leyenda', color: 'gris' },
    'Kingdra': { text: 'Leyenda', color: 'marron' },
    'Scizor': { text: 'Leyenda', color: 'azul' },
    'Tyranitar': { text: 'Leyenda', color: 'amarillo' },
    'Ampharos': { text: 'Leyenda', color: 'marron' },
    'Arcanine': { text: 'Leyenda', color: 'marron' },
    'Aerodactyl': { text: 'Leyenda', color: 'marron' },
    'Garchomp': { text: 'Leyenda', color: 'celeste' },
    'Haxorus': { text: 'Leyenda', color: 'verde' },
  },
  'Lance_2': {
    'Lapras': { text: 'Leyenda', color: 'marron' },
    'Dragonite': { text: 'Leyenda', color: 'celeste' },
    'Lucario': { text: 'Leyenda', color: 'rojo' },
    'Steelix': { text: 'Leyenda', color: 'azul' },
    'Eelektross': { text: 'Leyenda', color: 'celeste' },
    'Metagross': { text: 'Leyenda', color: 'rojo' },
    'Electivire': { text: 'Leyenda', color: 'celeste' },
    'Infernape': { text: 'Leyenda', color: 'gris' },
    'Gyarados': { text: 'Leyenda', color: 'celeste' },
    'Hydreigon': { text: 'Leyenda', color: 'marron' },
    'Arbok': { text: 'Leyenda', color: 'morado' },
    'Charizard': { text: 'Leyenda', color: 'rojo' },
    'Scrafty': { text: 'Leyenda', color: 'marron' },
    'Feraligatr': { text: 'Leyenda', color: 'rojo' },
    'Kingdra': { text: 'Leyenda', color: 'celeste' },
    'Scizor': { text: 'Leyenda', color: 'marron' },
    'Tyranitar': { text: 'Leyenda', color: 'azul' },
    'Ampharos': { text: 'Leyenda', color: 'marron' },
    'Arcanine': { text: 'Leyenda', color: 'verde' },
    'Aerodactyl': { text: 'Leyenda', color: 'gris' },
    'Garchomp': { text: 'Leyenda', color: 'amarillo' },
    'Haxorus': { text: 'Leyenda', color: 'celeste' },
    'Flygon': { text: 'Leyenda', color: 'celeste' },
    'Kangaskhan': { text: 'Leyenda', color: 'marron' },
  },
  'Blue': {
    'Exeggutor': { text: 'Leyenda', color: 'gris' },
    'Magnezone': { text: 'Leyenda', color: 'amarillo' },
    'Nidoking': { text: 'Leyenda', color: 'gris' },
    'Machamp': { text: 'Leyenda', color: 'gris' },
    'Blastoise': { text: 'Leyenda', color: 'azul' },
    'Electivire': { text: 'Leyenda', color: 'rojo' },
    'Rhyperior': { text: 'Leyenda', color: 'verde' },
    'Gyarados': { text: 'Leyenda', color: 'morado' },
    'Alakazam': { text: 'Leyenda', color: 'celeste' },
    'Umbreon': { text: 'Leyenda', color: 'marron' },
    'Charizard': { text: 'Leyenda', color: 'gris' },
    'Kingdra': { text: 'Leyenda', color: 'marron' },
    'Scizor': { text: 'Leyenda', color: 'marron' },
    'Tyranitar': { text: 'Leyenda', color: 'marron' },
    'Arcanine': { text: 'Leyenda', color: 'verde' },
    'Pidgeot': { text: 'Leyenda', color: 'marron' },
    'Espeon': { text: 'Leyenda', color: 'amarillo' },
    'Jolteon': { text: 'Leyenda', color: 'gris' },
    'Sandslash': { text: 'Leyenda', color: 'marron' },
    'Venusaur': { text: 'Leyenda', color: 'morado' },
    'Skarmory': { text: 'Leyenda', color: 'marron' },
    'Leafeon': { text: 'Leyenda', color: 'morado' },
    'Flareon': { text: 'Leyenda', color: 'marron' },
    'Poliwrath': { text: 'Leyenda', color: 'marron' },
    'Politoed': { text: 'Leyenda', color: 'marron' },
    'Vaporeon': { text: 'Leyenda', color: 'verde' },
    'Golem': { text: 'Leyenda', color: 'marron' },
    'Ninetales': { text: 'Leyenda', color: 'marron' },
  },
  'Will': {
    'Exeggutor': { text: 'Leyenda', color: 'marron' },
    'Magnezone': { text: 'Leyenda', color: 'marron' },
    'Golduck': { text: 'Leyenda', color: 'celeste' },
    'Mantine': { text: 'Leyenda', color: 'morado' },
    'Jynx': { text: 'Leyenda', color: 'marron' },
    'Bronzong': { text: 'Leyenda', color: 'celeste' },
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Claydol': { text: 'Leyenda', color: 'marron' },
    'Slowbro': { text: 'Leyenda', color: 'azul' },
    'Chansey': { text: 'Leyenda', color: 'gris' },
    'Electivire': { text: 'Leyenda', color: 'rojo' },
    'Umbreon': { text: 'Leyenda', color: 'celeste' },
    'Espeon': { text: 'Leyenda', color: 'amarillo' },
    'Jolteon': { text: 'Leyenda', color: 'verde' },
    'Flareon': { text: 'Leyenda', color: 'azul' },
    'Absol': { text: 'Leyenda', color: 'marron' },
    'Golurk': { text: 'Leyenda', color: 'marron' },
    'Empoleon': { text: 'Leyenda', color: 'amarillo' },
    'Altaria': { text: 'Leyenda', color: 'azul' },
    'Gardevoir': { text: 'Leyenda', color: 'verde' },
    'Liepard': { text: 'Leyenda', color: 'marron' },
    'Typhlosion': { text: 'Leyenda', color: 'marron' },
    'Girafarig': { text: 'Leyenda', color: 'marron' },
    'Clefable': { text: 'Leyenda', color: 'marron' },
    'Xatu': { text: 'Leyenda', color: 'marron' },
    'Hypno': { text: 'Leyenda', color: 'marron' },
    'Grumpig': { text: 'Leyenda', color: 'celeste' },
  },
  'Koga': {
    'Nidoking': { text: 'Leyenda', color: 'rojo' },
    'Lapras': { text: 'Leyenda', color: 'rosado' },
    'Nidoqueen': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'rojo' },
    'Muk': { text: 'Leyenda', color: 'verde' },
    'Gliscor': { text: 'Leyenda', color: 'marron' },
    'Rhyperior': { text: 'Leyenda', color: 'morado' },
    'Gengar': { text: 'Leyenda', color: 'celeste' },
    'Crobat': { text: 'Leyenda', color: 'gris' },
    'Scizor': { text: 'Leyenda', color: 'gris' },
    'Skarmory': { text: 'Leyenda', color: 'marron' },
    'Ninetales': { text: 'Leyenda', color: 'azul' },
    'Tentacruel': { text: 'Leyenda', color: 'marron' },
    'Sharpedo': { text: 'Leyenda', color: 'morado' },
    'Lanturn': { text: 'Leyenda', color: 'marron' },
    'Starmie': { text: 'Leyenda', color: 'marron' },
    'Bisharp': { text: 'Leyenda', color: 'marron' },
    'Samurott': { text: 'Leyenda', color: 'rojo' },
    'Forretress': { text: 'Leyenda', color: 'marron' },
    'Skuntank': { text: 'Leyenda', color: 'rojo' },
    'Ferrothorn': { text: 'Leyenda', color: 'marron' },
    'Tangrowth': { text: 'Leyenda', color: 'marron' },
    'Parasect': { text: 'Leyenda', color: 'celeste' },
    'Magmortar': { text: 'Leyenda', color: 'marron' },
    'Hypno': { text: 'Leyenda', color: 'amarillo' },
    'Ariados': { text: 'Leyenda', color: 'marron' },
    'Ditto': { text: 'Leyenda', color: 'morado' },
    'Venomoth': { text: 'Leyenda', color: 'marron' },
    'Stunfisk': { text: 'Leyenda', color: 'morado' },
    'Swalot': { text: 'Leyenda', color: 'celeste' },
    'Weezing': { text: 'Leyenda', color: 'marron' },
    'Electrode': { text: 'Leyenda', color: 'marron' },
  },
  'Karen': {
    'Weavile': { text: 'Leyenda', color: 'rojo' },
    'Lucario': { text: 'Leyenda', color: 'verde' },
    'Slowbro': { text: 'Leyenda', color: 'rojo' },
    'Vileplume': { text: 'Leyenda', color: 'marron' },
    'Blastoise': { text: 'Leyenda', color: 'azul' },
    'Salamence': { text: 'Leyenda', color: 'celeste' },
    'Rhyperior': { text: 'Leyenda', color: 'marron' },
    'Gyarados': { text: 'Leyenda', color: 'gris' },
    'Gengar': { text: 'Leyenda', color: 'amarillo' },
    'Hydreigon': { text: 'Leyenda', color: 'gris' },
    'Umbreon': { text: 'Leyenda', color: 'marron' },
    'Mismagius': { text: 'Leyenda', color: 'marron' },
    'Houndoom': { text: 'Leyenda', color: 'marron' },
    'Feraligatr': { text: 'Leyenda', color: 'marron' },
    'Tyranitar': { text: 'Leyenda', color: 'marron' },
    'Garchomp': { text: 'Leyenda', color: 'gris' },
    'Leafeon': { text: 'Leyenda', color: 'celeste' },
    'Flareon': { text: 'Leyenda', color: 'morado' },
    'Sableye': { text: 'Leyenda', color: 'marron' },
    'Absol': { text: 'Leyenda', color: 'celeste' },
    'Luxray': { text: 'Leyenda', color: 'gris' },
    'Excadrill': { text: 'Leyenda', color: 'rojo' },
    'Honchkrow': { text: 'Leyenda', color: 'marron' },
    'Gallade': { text: 'Leyenda', color: 'marron' },
    'Quagsire': { text: 'Leyenda', color: 'morado' },
    'Electrode': { text: 'Leyenda', color: 'rosado' },
    'Primeape': { text: 'Leyenda', color: 'amarillo' },
    'Victreebel': { text: 'Leyenda', color: 'gris' },
  },
  'Sidney': {
    'Magnezone': { text: 'Leyenda', color: 'azul' },
    'Hariyama': { text: 'Leyenda', color: 'verde' },
    'Darmanitan': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'amarillo' },
    'Electivire': { text: 'Leyenda', color: 'gris' },
    'Aggron': { text: 'Leyenda', color: 'marron' },
    'Salamence': { text: 'Leyenda', color: 'celeste' },
    'Gyarados': { text: 'Leyenda', color: 'marron' },
    'Shiftry': { text: 'Leyenda', color: 'marron' },
    'Toxicroak': { text: 'Leyenda', color: 'rojo' },
    'Mandibuzz': { text: 'Leyenda', color: 'celeste' },
    'Scrafty': { text: 'Leyenda', color: 'marron' },
    'Scizor': { text: 'Leyenda', color: 'morado' },
    'Garchomp': { text: 'Leyenda', color: 'celeste' },
    'Sableye': { text: 'Leyenda', color: 'gris' },
    'Absol': { text: 'Leyenda', color: 'marron' },
    'Tentacruel': { text: 'Leyenda', color: 'marron' },
    'Luxray': { text: 'Leyenda', color: 'celeste' },
    'Cacturne': { text: 'Leyenda', color: 'celeste' },
    'Golurk': { text: 'Leyenda', color: 'rojo' },
    'Mightyena': { text: 'Leyenda', color: 'celeste' },
    'Spiritomb': { text: 'Leyenda', color: 'marron' },
    'Mienshao': { text: 'Leyenda', color: 'celeste' },
    'Huntail': { text: 'Leyenda', color: 'marron' },
    'Excadrill': { text: 'Leyenda', color: 'celeste' },
    'Crawdaunt': { text: 'Leyenda', color: 'rojo' },
    'Scolipede': { text: 'Leyenda', color: 'marron' },
    'Sharpedo': { text: 'Leyenda', color: 'rojo' },
  },
  'Phoebe': {
    'Banette': { text: 'Leyenda', color: 'celeste' },
    'Lucario': { text: 'Leyenda', color: 'rojo' },
    'Raichu': { text: 'Leyenda', color: 'marron' },
    'Hydreigon': { text: 'Leyenda', color: 'verde' },
    'Rotom Lavadora': { text: 'Leyenda', color: 'marron' },
    'Umbreon': { text: 'Leyenda', color: 'gris' },
    'Mismagius': { text: 'Leyenda', color: 'celeste' },
    'Mandibuzz': { text: 'Leyenda', color: 'rojo' },
    'Houndoom': { text: 'Leyenda', color: 'marron' },
    'Arcanine': { text: 'Leyenda', color: 'rojo' },
    'Ninetales': { text: 'Leyenda', color: 'marron' },
    'Sableye': { text: 'Leyenda', color: 'celeste' },
    'Luxray': { text: 'Leyenda', color: 'marron' },
    'Mawile': { text: 'Leyenda', color: 'marron' },
    'Froslass': { text: 'Leyenda', color: 'celeste' },
    'Dusknoir': { text: 'Leyenda', color: 'amarillo' },
    'Regice': { text: 'Leyenda', color: 'celeste' },
    'Chandelure': { text: 'Leyenda', color: 'rojo' },
    'Meganium': { text: 'Leyenda', color: 'marron' },
    'Honchkrow': { text: 'Leyenda', color: 'marron' },
  },
  'Glacia': {
    'Togekiss': { text: 'Leyenda', color: 'marron' },
    'Hariyama': { text: 'Leyenda', color: 'marron' },
    'Nidoqueen': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'rojo' },
    'Mismagius': { text: 'Leyenda', color: 'marron' },
    'Skarmory': { text: 'Leyenda', color: 'marron' },
    'Mienshao': { text: 'Leyenda', color: 'marron' },
    'Froslass': { text: 'Leyenda', color: 'celeste' },
    'Abomasnow': { text: 'Leyenda', color: 'marron' },
    'Walrein': { text: 'Leyenda', color: 'marron' },
    'Lanturn': { text: 'Leyenda', color: 'celeste' },
    'Serperior': { text: 'Leyenda', color: 'amarillo' },
    'Vanilluxe': { text: 'Leyenda', color: 'marron' },
    'Gallade': { text: 'Leyenda', color: 'verde' },
    'Altaria': { text: 'Leyenda', color: 'marron' },
    'Glalie': { text: 'Leyenda', color: 'marron' },
    'Blissey': { text: 'Leyenda', color: 'celeste' },
    'Beartic': { text: 'Leyenda', color: 'azul' },
  },
  'Drake': {
    'Nidoking': { text: 'Leyenda', color: 'marron' },
    'Lapras': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'azul' },
    'Eelektross': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'marron' },
    'Aggron': { text: 'Leyenda', color: 'marron' },
    'Salamence': { text: 'Leyenda', color: 'marron' },
    'Krookodile': { text: 'Leyenda', color: 'rojo' },
    'Feraligatr': { text: 'Leyenda', color: 'morado' },
    'Kingdra': { text: 'Leyenda', color: 'celeste' },
    'Ampharos': { text: 'Leyenda', color: 'marron' },
    'Haxorus': { text: 'Leyenda', color: 'marron' },
    'Empoleon': { text: 'Leyenda', color: 'marron' },
    'Gallade': { text: 'Leyenda', color: 'celeste' },
    'Altaria': { text: 'Leyenda', color: 'celeste' },
    'Regirock': { text: 'Leyenda', color: 'rojo' },
    'Torkoal': { text: 'Leyenda', color: 'marron' },
    'Seviper': { text: 'Leyenda', color: 'rojo' },
    'Floatzel': { text: 'Leyenda', color: 'marron' },
    'Sceptile': { text: 'Leyenda', color: 'marron' },
    'Flygon': { text: 'Leyenda', color: 'celeste' },
  },
  'Wallace': {
    'Togekiss': { text: 'Leyenda', color: 'marron' },
    'Dragonite': { text: 'Leyenda', color: 'celeste' },
    'Eelektross': { text: 'Leyenda', color: 'celeste' },
    'Metagross': { text: 'Leyenda', color: 'marron' },
    'Gyarados': { text: 'Leyenda', color: 'celeste' },
    'Tentacruel': { text: 'Leyenda', color: 'rojo' },
    'Mienshao': { text: 'Leyenda', color: 'marron' },
    'Empoleon': { text: 'Leyenda', color: 'marron' },
    'Walrein': { text: 'Leyenda', color: 'marron' },
    'Lanturn': { text: 'Leyenda', color: 'celeste' },
    'Serperior': { text: 'Leyenda', color: 'azul' },
    'Altaria': { text: 'Leyenda', color: 'marron' },
    'Swampert': { text: 'Leyenda', color: 'marron' },
    'Registeel': { text: 'Leyenda', color: 'marron' },
    'Milotic': { text: 'Leyenda', color: 'marron' },
    'Seaking': { text: 'Leyenda', color: 'celeste' },
    'Roserade': { text: 'Leyenda', color: 'marron' },
    'Wailord': { text: 'Leyenda', color: 'marron' },
    'Starmie': { text: 'Leyenda', color: 'marron' },
    'Ludicolo': { text: 'Leyenda', color: 'celeste' },
    'Whiscash': { text: 'Leyenda', color: 'marron' },
    'Gardevoir': { text: 'Leyenda', color: 'rojo' },
  },
  'Aaron': {
    'Steelix': { text: 'Leyenda', color: 'rojo' },
    'Gliscor': { text: 'Leyenda', color: 'marron' },
    'Heracross': { text: 'Leyenda', color: 'celeste' },
    'Drapion': { text: 'Leyenda', color: 'marron' },
    'Scizor': { text: 'Leyenda', color: 'marron' },
    'Tyranitar': { text: 'Leyenda', color: 'marron' },
    'Kingler': { text: 'Leyenda', color: 'marron' },
    'Crawdaunt': { text: 'Leyenda', color: 'celeste' },
    'Sceptile': { text: 'Leyenda', color: 'marron' },
    'Flygon': { text: 'Leyenda', color: 'marron' },
    'Volcarona': { text: 'Leyenda', color: 'marron' },
    'Escavalier': { text: 'Leyenda', color: 'marron' },
    'Vespiquen': { text: 'Leyenda', color: 'marron' },
    'Omastar': { text: 'Leyenda', color: 'marron' },
    'Durant': { text: 'Leyenda', color: 'celeste' },
    'Kabutops': { text: 'Leyenda', color: 'marron' },
    'Forretress': { text: 'Leyenda', color: 'marron' },
    'Skuntank': { text: 'Leyenda', color: 'marron' },
    'Crustle': { text: 'Leyenda', color: 'rojo' },
    'Octillery': { text: 'Leyenda', color: 'marron' },
    'Scyther': { text: 'Leyenda', color: 'marron' },
    'Gastrodon': { text: 'Leyenda', color: 'marron' },
    'Ferrothorn': { text: 'Leyenda', color: 'celeste' },
    'Beautifly': { text: 'Leyenda', color: 'amarillo' },
    'Yanmega': { text: 'Leyenda', color: 'marron' },
    'Dustox': { text: 'Leyenda', color: 'marron' },
  },
  'Bertha': {
    'Nidoking': { text: 'Leyenda', color: 'marron' },
    'Bronzong': { text: 'Leyenda', color: 'marron' },
    'Cloyster': { text: 'Leyenda', color: 'marron' },
    'Steelix': { text: 'Leyenda', color: 'marron' },
    'Blastoise': { text: 'Leyenda', color: 'marron' },
    'Gliscor': { text: 'Leyenda', color: 'azul' },
    'Seismitoad': { text: 'Leyenda', color: 'marron' },
    'Rhyperior': { text: 'Leyenda', color: 'marron' },
    'Gengar': { text: 'Leyenda', color: 'marron' },
    'Skarmory': { text: 'Leyenda', color: 'marron' },
    'Golem': { text: 'Leyenda', color: 'marron' },
    'Sableye': { text: 'Leyenda', color: 'marron' },
    'Absol': { text: 'Leyenda', color: 'morado' },
    'Walrein': { text: 'Leyenda', color: 'marron' },
    'Whiscash': { text: 'Leyenda', color: 'rojo' },
    'Druddigon': { text: 'Leyenda', color: 'marron' },
    'Durant': { text: 'Leyenda', color: 'celeste' },
    'Forretress': { text: 'Leyenda', color: 'marron' },
    'Tangrowth': { text: 'Leyenda', color: 'marron' },
    'Camerupt': { text: 'Leyenda', color: 'marron' },
    'Quagsire': { text: 'Leyenda', color: 'marron' },
    'Emboar': { text: 'Leyenda', color: 'marron' },
    'Sudowoodo': { text: 'Leyenda', color: 'marron' },
    'Parasect': { text: 'Leyenda', color: 'marron' },
    'Hippowdon': { text: 'Leyenda', color: 'marron' },
    'Amoonguss': { text: 'Leyenda', color: 'marron' },
    'Donphan': { text: 'Leyenda', color: 'marron' },
  },
  'Flint': {
    'Bronzong': { text: 'Leyenda', color: 'marron' },
    'Dragonite': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'azul' },
    'Steelix': { text: 'Leyenda', color: 'marron' },
    'Salamence': { text: 'Leyenda', color: 'marron' },
    'Infernape': { text: 'Leyenda', color: 'rojo' },
    'Rotom Horno': { text: 'Leyenda', color: 'marron' },
    'Houndoom': { text: 'Leyenda', color: 'marron' },
    'Charizard': { text: 'Leyenda', color: 'marron' },
    'Arcanine': { text: 'Leyenda', color: 'marron' },
    'Haxorus': { text: 'Leyenda', color: 'marron' },
    'Flareon': { text: 'Leyenda', color: 'marron' },
    'Ninetales': { text: 'Leyenda', color: 'marron' },
    'Cacturne': { text: 'Leyenda', color: 'marron' },
    'Ludicolo': { text: 'Leyenda', color: 'marron' },
    'Drifblim': { text: 'Leyenda', color: 'marron' },
    'Entei': { text: 'Leyenda', color: 'marron' },
    'Conkeldurr': { text: 'Leyenda', color: 'marron' },
    'Medicham': { text: 'Leyenda', color: 'marron' },
    'Bouffalant': { text: 'Leyenda', color: 'marron' },
    'Camerupt': { text: 'Leyenda', color: 'marron' },
    'Magmortar': { text: 'Leyenda', color: 'marron' },
    'Rapidash': { text: 'Leyenda', color: 'marron' },
    'Maractus': { text: 'Leyenda', color: 'marron' },
    'Lopunny': { text: 'Leyenda', color: 'marron' },
    'Typhlosion': { text: 'Leyenda', color: 'marron' },
    'Blaziken': { text: 'Leyenda', color: 'marron' },
  },
  'Lucian': {
    'Golduck': { text: 'Leyenda', color: 'marron' },
    'Bronzong': { text: 'Leyenda', color: 'marron' },
    'Dragonite': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Raichu': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'marron' },
    'Alakazam': { text: 'Leyenda', color: 'marron' },
    'Hydreigon': { text: 'Leyenda', color: 'marron' },
    'Mismagius': { text: 'Leyenda', color: 'marron' },
    'Espeon': { text: 'Leyenda', color: 'marron' },
    'Ninetales': { text: 'Leyenda', color: 'marron' },
    'Absol': { text: 'Leyenda', color: 'marron' },
    'Empoleon': { text: 'Leyenda', color: 'marron' },
    'Gallade': { text: 'Leyenda', color: 'marron' },
    'Gardevoir': { text: 'Leyenda', color: 'marron' },
    'Sigilyph': { text: 'Leyenda', color: 'marron' },
    'Medicham': { text: 'Leyenda', color: 'marron' },
    'Noctowl': { text: 'Leyenda', color: 'marron' },
    'Girafarig': { text: 'Leyenda', color: 'marron' },
    'Kecleon': { text: 'Leyenda', color: 'marron' },
    'Stantler': { text: 'Leyenda', color: 'marron' },
  },
  'Cynthia': {
    'Lapras': { text: 'Leyenda', color: 'marron' },
    'Togekiss': { text: 'Leyenda', color: 'marron' },
    'Nidoqueen': { text: 'Leyenda', color: 'marron' },
    'Bronzong': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Eelektross': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'marron' },
    'Heracross': { text: 'Leyenda', color: 'marron' },
    'Umbreon': { text: 'Leyenda', color: 'marron' },
    'Mismagius': { text: 'Leyenda', color: 'marron' },
    'Tyranitar': { text: 'Leyenda', color: 'marron' },
    'Arcanine': { text: 'Leyenda', color: 'marron' },
    'Aerodactyl': { text: 'Leyenda', color: 'marron' },
    'Garchomp': { text: 'Leyenda', color: 'marron' },
    'Glaceon': { text: 'Leyenda', color: 'marron' },
    'Spiritomb': { text: 'Leyenda', color: 'marron' },
    'Excadrill': { text: 'Leyenda', color: 'marron' },
    'Chandelure': { text: 'Leyenda', color: 'marron' },
    'Serperior': { text: 'Leyenda', color: 'marron' },
    'Altaria': { text: 'Leyenda', color: 'marron' },
    'Milotic': { text: 'Leyenda', color: 'marron' },
    'Roserade': { text: 'Leyenda', color: 'marron' },
    'Jellicent': { text: 'Leyenda', color: 'marron' },
    'Braviary': { text: 'Leyenda', color: 'marron' },
    'Gastrodon': { text: 'Leyenda', color: 'marron' },
    'Lickilicky': { text: 'Leyenda', color: 'marron' },
    'Bastiodon': { text: 'Leyenda', color: 'marron' },
    'Clefable': { text: 'Leyenda', color: 'marron' },
    'Rayquaza': { text: 'Leyenda', color: 'marron' },
  },
  'Shauntal': {
    'Bronzong': { text: 'Leyenda', color: 'marron' },
    'Banette': { text: 'Leyenda', color: 'marron' },
    'Dragonite': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Eelektross': { text: 'Leyenda', color: 'marron' },
    'Gengar': { text: 'Leyenda', color: 'marron' },
    'Hydreigon': { text: 'Leyenda', color: 'marron' },
    'Rotom Lavadora': { text: 'Leyenda', color: 'marron' },
    'Umbreon': { text: 'Leyenda', color: 'marron' },
    'Mismagius': { text: 'Leyenda', color: 'marron' },
    'Toxicroak': { text: 'Leyenda', color: 'marron' },
    'Jolteon': { text: 'Leyenda', color: 'marron' },
    'Absol': { text: 'Leyenda', color: 'marron' },
    'Luxray': { text: 'Leyenda', color: 'marron' },
    'Golurk': { text: 'Leyenda', color: 'marron' },
    'Froslass': { text: 'Leyenda', color: 'marron' },
    'Chandelure': { text: 'Leyenda', color: 'marron' },
    'Milotic': { text: 'Leyenda', color: 'marron' },
    'Purugly': { text: 'Leyenda', color: 'marron' },
    'Bisharp': { text: 'Leyenda', color: 'marron' },
    'Drifblim': { text: 'Leyenda', color: 'marron' },
    'Liepard': { text: 'Leyenda', color: 'marron' },
  },
  'Grimsley': {
    'Staraptor': { text: 'Leyenda', color: 'marron' },
    'Salamence': { text: 'Leyenda', color: 'marron' },
    'Krookodile': { text: 'Leyenda', color: 'marron' },
    'Gyarados': { text: 'Leyenda', color: 'marron' },
    'Mismagius': { text: 'Leyenda', color: 'marron' },
    'Houndoom': { text: 'Leyenda', color: 'marron' },
    'Crobat': { text: 'Leyenda', color: 'marron' },
    'Scrafty': { text: 'Leyenda', color: 'marron' },
    'Kingdra': { text: 'Leyenda', color: 'marron' },
    'Tyranitar': { text: 'Leyenda', color: 'marron' },
    'Garchomp': { text: 'Leyenda', color: 'marron' },
    'Haxorus': { text: 'Leyenda', color: 'marron' },
    'Espeon': { text: 'Leyenda', color: 'marron' },
    'Absol': { text: 'Leyenda', color: 'marron' },
    'Luxray': { text: 'Leyenda', color: 'marron' },
    'Spiritomb': { text: 'Leyenda', color: 'marron' },
    'Sharpedo': { text: 'Leyenda', color: 'marron' },
    'Chandelure': { text: 'Leyenda', color: 'marron' },
    'Honchkrow': { text: 'Leyenda', color: 'marron' },
    'Serperior': { text: 'Leyenda', color: 'marron' },
    'Roserade': { text: 'Leyenda', color: 'marron' },
    'Bisharp': { text: 'Leyenda', color: 'marron' },
    'Liepard': { text: 'Leyenda', color: 'marron' },
    'Samurott': { text: 'Leyenda', color: 'marron' },
  },
  'Caitlin': {
    'Togekiss': { text: 'Leyenda', color: 'marron' },
    'Nidoqueen': { text: 'Leyenda', color: 'marron' },
    'Bronzong': { text: 'Leyenda', color: 'marron' },
    'Raichu': { text: 'Leyenda', color: 'marron' },
    'Staraptor': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'marron' },
    'Alakazam': { text: 'Leyenda', color: 'marron' },
    'Umbreon': { text: 'Leyenda', color: 'marron' },
    'Houndoom': { text: 'Leyenda', color: 'marron' },
    'Jolteon': { text: 'Leyenda', color: 'marron' },
    'Leafeon': { text: 'Leyenda', color: 'marron' },
    'Vaporeon': { text: 'Leyenda', color: 'marron' },
    'Absol': { text: 'Leyenda', color: 'marron' },
    'Mienshao': { text: 'Leyenda', color: 'marron' },
    'Slowking': { text: 'Leyenda', color: 'marron' },
    'Snorlax': { text: 'Leyenda', color: 'marron' },
    'Cinccino': { text: 'Leyenda', color: 'marron' },
    'Sigilyph': { text: 'Leyenda', color: 'marron' },
    'Reuniclus': { text: 'Leyenda', color: 'marron' },
    'Emolga': { text: 'Leyenda', color: 'marron' },
    'Entei': { text: 'Leyenda', color: 'marron' },
    'Gothitelle': { text: 'Leyenda', color: 'marron' },
    'Musharna': { text: 'Leyenda', color: 'marron' },
  },
  'Marshal': {
    'Magnezone': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Machamp': { text: 'Leyenda', color: 'marron' },
    'Metagross': { text: 'Leyenda', color: 'marron' },
    'Gliscor': { text: 'Leyenda', color: 'marron' },
    'Electivire': { text: 'Leyenda', color: 'marron' },
    'Aggron': { text: 'Leyenda', color: 'marron' },
    'Salamence': { text: 'Leyenda', color: 'marron' },
    'Seismitoad': { text: 'Leyenda', color: 'marron' },
    'Krookodile': { text: 'Leyenda', color: 'marron' },
    'Gyarados': { text: 'Leyenda', color: 'marron' },
    'Toxicroak': { text: 'Leyenda', color: 'marron' },
    'Tyranitar': { text: 'Leyenda', color: 'marron' },
    'Haxorus': { text: 'Leyenda', color: 'marron' },
    'Skarmory': { text: 'Leyenda', color: 'marron' },
    'Luxray': { text: 'Leyenda', color: 'marron' },
    'Golurk': { text: 'Leyenda', color: 'marron' },
    'Mienshao': { text: 'Leyenda', color: 'marron' },
    'Crawdaunt': { text: 'Leyenda', color: 'marron' },
    'Dusknoir': { text: 'Leyenda', color: 'marron' },
    'Carracosta': { text: 'Leyenda', color: 'marron' },
    'Conkeldurr': { text: 'Leyenda', color: 'marron' },
    'Sawk': { text: 'Leyenda', color: 'marron' },
    'Throh': { text: 'Leyenda', color: 'marron' },
    'Breloom': { text: 'Leyenda', color: 'marron' },
    'Medicham': { text: 'Leyenda', color: 'marron' },
  },
  'Alder': {
    'Dragonite': { text: 'Leyenda', color: 'marron' },
    'Lucario': { text: 'Leyenda', color: 'marron' },
    'Seismitoad': { text: 'Leyenda', color: 'marron' },
    'Krookodile': { text: 'Leyenda', color: 'marron' },
    'Feraligatr': { text: 'Leyenda', color: 'marron' },
    'Sandslash': { text: 'Leyenda', color: 'marron' },
    'Vaporeon': { text: 'Leyenda', color: 'marron' },
    'Excadrill': { text: 'Leyenda', color: 'marron' },
    'Chandelure': { text: 'Leyenda', color: 'marron' },
    'Vanilluxe': { text: 'Leyenda', color: 'marron' },
    'Floatzel': { text: 'Leyenda', color: 'marron' },
    'Samurott': { text: 'Leyenda', color: 'marron' },
    'Reuniclus': { text: 'Leyenda', color: 'gris' },
    'Conkeldurr': { text: 'Leyenda', color: 'celeste' },
    'Druddigon': { text: 'Leyenda', color: 'marron' },
    'Archeops': { text: 'Leyenda', color: 'gris' },
    'Volcarona': { text: 'Leyenda', color: 'rojo' },
    'Manectric': { text: 'Leyenda', color: 'verde' },
    'Bouffalant': { text: 'Leyenda', color: 'gris' },
    'Latias': { text: 'Leyenda', color: 'celeste' },
    'Escavalier': { text: 'Leyenda', color: 'gris' },
    'Latios': { text: 'Leyenda', color: 'verde' },
    'Accelgor': { text: 'Leyenda', color: 'azul' },
    'Gigalith': { text: 'Leyenda', color: 'azul' },
    'Braviary': { text: 'Leyenda', color: 'rosado' },
  },
};

